# Generated by Django 3.0.2 on 2020-02-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
    ]
