# Generated by Django 3.0.2 on 2020-02-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Descuento %'),
        ),
    ]
