# Generated by Django 3.0.2 on 2020-02-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200131_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
    ]
