# Generated by Django 3.0.2 on 2020-02-03 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200131_2259'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getProducts', to='companies.Company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='profitproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='getProductProficts', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='profitproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='getUserProficts', to=settings.AUTH_USER_MODEL),
        ),
    ]
