# Generated by Django 3.0.2 on 2020-02-20 00:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200203_1756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profitproduct',
            unique_together={('user', 'product')},
        ),
    ]
