# Generated by Django 3.0.2 on 2020-01-29 01:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_auto_20180717_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access',
            field=models.CharField(choices=[('admin', 'Administrador'), ('collaborator', 'Colaborador'), ('other', 'otro')], default='collaborator', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Cumpleaños'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cc',
            field=models.PositiveIntegerField(blank=True, error_messages={'unique': 'Esta cedula ya tiene vinculada una cuenta.'}, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='getEmployees', to='companies.Company', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='getProfiles', to='companies.Occupation', verbose_name='Ocupación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
