# Generated by Django 3.0.2 on 2020-02-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200128_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
    ]
