# Generated by Django 3.0.2 on 2020-01-29 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='getCompanyPayments', to='companies.Company', verbose_name='Empresa')),
                ('paymentManager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='getManagerPayments', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='getUserPayments', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
